name: create-release
on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Publish to Maven Central
      - uses: actions/checkout@v2
      - name: Set up maven settings.xml
        id: setup_maven
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: oss.sonatype.org
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Publish to Maven Central
        id: publish_package
        run: mvn verify -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} -PmavenCentral
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASS }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}