name: create-release
on:
  workflow_dispatch:
    inputs:
      version:
        description: Bump Version
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Publish to Maven Central
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        id: setup_maven
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: gpg.passphrase
          server-passphrase: mljetovanje
          gpg-private-key: ${{ secrets.GPG_KEYNAME }}
      - name: Print settings.xml
        run: cat /home/runner/.m2/settings.xml
      - name: Publish package
        id: publish_package
        run: mvn --batch-mode -Dgpg.passphrase=mljetovanje verify -PmavenCentral
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASS }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}